// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhziixsrIqrNfVMkb1XJdMzkAalnHjPto',
    appId: '1:134675558444:web:88ebfa54be85303aec6189',
    messagingSenderId: '134675558444',
    projectId: 'zylu-56a8d',
    authDomain: 'zylu-56a8d.firebaseapp.com',
    storageBucket: 'zylu-56a8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTa-uQdLU6QR8Mt_S1Wvyy7A2os5hwiqk',
    appId: '1:134675558444:android:79624f0647c6eeccec6189',
    messagingSenderId: '134675558444',
    projectId: 'zylu-56a8d',
    storageBucket: 'zylu-56a8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg7GUW3lnq5GjVV1E30hGg5tvHlOXvf2w',
    appId: '1:134675558444:ios:da1d29ef6f894827ec6189',
    messagingSenderId: '134675558444',
    projectId: 'zylu-56a8d',
    storageBucket: 'zylu-56a8d.firebasestorage.app',
    androidClientId:
        '134675558444-b73980or2cn96kqukbc2jp0hsgr4nnu1.apps.googleusercontent.com',
    iosClientId:
        '134675558444-tusd8pl644hknei01t6ksjibluiv16bi.apps.googleusercontent.com',
    iosBundleId: 'com.gobi.zylu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg7GUW3lnq5GjVV1E30hGg5tvHlOXvf2w',
    appId: '1:134675558444:ios:da1d29ef6f894827ec6189',
    messagingSenderId: '134675558444',
    projectId: 'zylu-56a8d',
    storageBucket: 'zylu-56a8d.firebasestorage.app',
    androidClientId:
        '134675558444-b73980or2cn96kqukbc2jp0hsgr4nnu1.apps.googleusercontent.com',
    iosClientId:
        '134675558444-tusd8pl644hknei01t6ksjibluiv16bi.apps.googleusercontent.com',
    iosBundleId: 'com.gobi.zylu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhziixsrIqrNfVMkb1XJdMzkAalnHjPto',
    appId: '1:134675558444:web:bc3e36523814d4aeec6189',
    messagingSenderId: '134675558444',
    projectId: 'zylu-56a8d',
    authDomain: 'zylu-56a8d.firebaseapp.com',
    storageBucket: 'zylu-56a8d.firebasestorage.app',
  );
}
